### ISSUE TITLE
DownZemAll AppImage does not run

### ISSUE THREAD

**Issue by probonopd** [setvisible/DownZemAll#13] opened 2020-08-02 22:32 UTC
DownZemAll AppImage does not run on Ubuntu xenial:

```
Fatal: This application failed to start because it could not find or load the Qt platform plugin "xcb".
```

Reference:
https://github.com/AppImage/appimage.github.io/pull/2192

**Comment by nicolaasjan** [comment] 2022-01-12 08:16
Same here in Linux Mint 19.3...

**Comment by setvisible** [comment] 2023-01-02 16:38
Duplicate of #78

**Closed by setvisible** 2023-01-02 16:38 UTC
