### ISSUE TITLE
Problem with DZA v3.0.5 windows mingw

### ISSUE THREAD

**Issue by HAMiDY25** [setvisible/DownZemAll#108] opened 2023-05-23 18:58 UTC
I have a problem.
I can't download any file in version 3.0.5.

![DownZemAll_v3 0 5_windows-mingw-x64-](https://github.com/setvisible/DownZemAll/assets/19431107/fdc15da9-e0fb-4c91-80d6-9cf350cb823c)

The previous versions work correctly.

![DownZemAll_v3 0 4_windows-mingw-x64](https://github.com/setvisible/DownZemAll/assets/19431107/b41bbdc5-4eb0-4427-94a9-33a1bc9ea98a)

OS: Windows 10 LTSC

**Comment by setvisible** [comment] 2023-06-06 18:18
Hi, thanks for reporting this issue.

It's a regression due to wrong signature of signals.

It will be fixed in v3.0.6 which is coming soon...

Regards,

**Closed** 2023-06-06 18:19 UTC
Labels: bug
