### ISSUE TITLE
Cannot make the extension work

### ISSUE THREAD

**Issue by knminhaz** [setvisible/DownZemAll#17] opened 2020-11-19 13:33 UTC
Hello. I am running Manjaro. Installed the program from AUR and the extension from Chrome store. The program works fine but cannot integrate with Chrome. What should I do? Thanks

**Comment by setvisible** [comment] 2020-11-22 12:08
Hi. Indeed the manifest (*.json) of the Chrome web extension wasn't deployed correctly. I pushed the fix (so should be fixed on next release). Meanwhile, you can update this file where your app is installed:

`<DZA path>/install.sh`

with this new code:
https://github.com/setvisible/DownZemAll/blob/develop/web-extension/setup/unix/install.sh

and rerun it, so that it installs the Chromium's `manifest.json` to:

`~/.config/chromium/NativeMessagingHosts/launcher-manifest-chrome.json`

Hope it helps.

**Comment by setvisible** [comment] 2020-11-22 12:11
Duplicate of #11

**Comment by yochananmarqos** [comment] 2020-11-28 21:10
@knminhaz Fixed in 2.1.0-2.

**Closed** 2020-12-07 20:52 UTC
Labels: bug
