### ISSUE TITLE
AppImage for 2.0.3

### ISSUE THREAD

**Issue by LukeZBaker** [setvisible/DownZemAll#9] opened 2020-06-16 15:56 UTC
Running the AppImage file generates the error:

```
Fatal: This application failed to start because it could not find or load the Qt platform plugin "xcb".

Reinstalling the application may fix this problem.
Aborted (core dumped)
```
However, (lib)xcb is installed. This is on the Arch distro.

**Comment by setvisible** [comment] 2020-06-17 18:58
Same error message on my side, on a Ubuntu VM.

There are missing dependencies in the AppImage build script I think.

**Comment by yochananmarqos** [comment] 2020-06-30 20:16
@LukeZBaker Since you're using Arch, you might be interested in my AUR package: [`downzemall`](https://aur.archlinux.org/packages/downzemall/).

**Comment by LukeZBaker** [comment] 2020-07-01 01:48
> @LukeZBaker Since you're using Arch, you might be interested in my AUR package: [`downzemall`](https://aur.archlinux.org/packages/downzemall/).

Thanks, I've installed it with your package. I wrote a review of DownZemAll! a few days ago, so I've referenced the AUR package.

**Comment by yochananmarqos** [comment] 2020-07-01 02:01
@LukeZBaker Your article is how I came across it actually. 😉

**Comment by setvisible** [comment] 2023-01-02 16:38
Duplicate of #78

**Closed by setvisible** 2023-01-02 16:38 UTC
