### ISSUE TITLE
Cannot run appimage

### ISSUE THREAD

**Issue by MorGotHMGH** [setvisible/DownZemAll#60] opened 2022-02-27 09:42 UTC
On Linux Mint 20.3 Cinnamon is error when trying to start appimage - "This application failed to start because it could not find or load the Qt platform plugin "xcb""

**Comment by MillironX** [comment] 2022-07-28 16:06
Same here. Fedora 36.

**Comment by setvisible** [comment] 2023-01-02 16:39
Duplicate of #78

**Closed by setvisible** 2023-01-02 16:39 UTC
Labels: bug, good first issue
