### ISSUE TITLE
[FR]: Update progress bar in realtime

### ISSUE THREAD

**Issue by RafaelLinux** [setvisible/DownZemAll#93] opened 2023-01-03 08:11 UTC
I don't know if it's a bug, but DZA shows a static stripped progress bar, instead a real or at least animated progress bar. User don't know if downloading is progressing or not just now.

Please, add in future this feature.

Thank you

**Comment by setvisible** [comment] 2023-04-01 15:06
Hi,

Need more info to reproduce it....

Suspect a problem with yt-dlp on certain sites.

If the issue only happen on some sites, the best is to address it to the project:
https://github.com/yt-dlp/yt-dlp

Regards

**Comment by RafaelLinux** [comment] 2023-04-03 02:14
I'll try to record issue with a large video. Usually it begins with a STATIC striped bar. Later, suddenly bar is filled.

**Comment by setvisible** [comment] 2023-05-08 11:33
Fixed in v3.0.4

**Closed by setvisible** 2023-05-08 11:33 UTC
Labels: bug

**Comment by RafaelLinux** [comment] 2023-05-08 22:19
Hi. It works, but not as it should!!!! Take a look to this screenshot. It's a downloading from [Youtube](https://www.youtube.com/watch?v=79wWy5HUJxU) of a video of 4.4GB. However, you can see in "Size" column that downloaded size (in progress) is GREATER than showed total size ,that is showed as 176MB.. In fact, while capturing screenshot, DZA continued downloading, despite progress column show "100%" (completed).  What is more, when I inspected target folder, a thousand 10MB files called "name_of_video_" with suffix from 1 to 49 and continue creating this sequence of files despite I closed DZA. I saw "yt-dl" process was active and I needed to kill it from "System activity" window.
![imagen](https://user-images.githubusercontent.com/13048959/236947863-301c0b22-5493-41f6-939f-d20126051244.png)

Using openSUSE Tumbleweed, DZA 3.0.4, yt-dlp 023.03.04-1.1

**Comment by setvisible** [comment] 2023-05-09 08:42
Hello

1. For the size:

try the command:

`yt-dlp.exe --dump-json https://www.youtube.com/watch?v=79wWy5HUJxU > log.txt`

See below : I isolated the file sizes + added some spaces to make it more readable:

```
"filesize_approx": 12 606 419 940,
"filesize":  35 935 772,
"filesize":  46 158 753,
"filesize":  56 948 829,
"filesize":  68 443 043,
"filesize":  94 622 698,
"filesize": 151 142 716,
"filesize": 185 165 466,
"filesize":  79 129 253,
"filesize":  34 655 131,
"filesize":  25 283 109,
"filesize":  63 754 586,
"filesize":  44 935 482,
"filesize":  68 520 287,
"filesize":  88 023 514,
"filesize": 100 968 220,
"filesize":  97 686 237,
"filesize": 184 621 316,
"filesize": 205 529 196,
"filesize": 584 274 504,
"filesize": 243 395 971,
"filesize": 341 990 946,
"filesize": 333 521 037,
"filesize": 366 573 712,
"filesize":        null,
```

This list is the metadata get by yt-dlp, from the data returned by the video server. Thus it doesn't return 4.4GB but values of some hundred MB... depending of the format choosen, the size might be said as 176.6MB. I think the issue is with yt-dlp or maybe the server simply lies.

There's no possibility to verify if the file size is correct before it's downloaded. We can only trust the metadata given by the server...


2. For the fragments:

Some servers might optimize the connection by cutting a large video into small fragments. So, yt-dlp has an option "--concurrent-fragment" to take advantage of this useful fragmentation, that permits to download them concurrently. I recently added this option parameter in Preferences > Network > Concurrent Fragments. These temporary fragments are removed once fully downloaded and concat into the final video file. There's a command to keep them `--keep-fragments ` but I don't think it's useful.

Doc:
https://github.com/yt-dlp/yt-dlp

Regards

**Comment by setvisible** [comment] 2023-05-09 08:50
Note: the 176.6MB ("filesize": 185165466) seems to be the audio size only ("format": "251 - audio only (medium)"). The filesize of the video only is not given apparently.

**Comment by RafaelLinux** [comment] 2023-05-09 21:17
I am glad you found the mistake !!!!! It was not so obvious and I wish to find it was not a headache ;) 
You explained it with great detail, thank you.

I was thinking strange files fragmentaion was even related to where I was downloading, and NFS shared folder, but I never have had issues such this before. Was an insane quantity of files, I think it should be optional in DZA interface (suggestion).

**Comment by RafaelLinux** [comment] 2023-05-10 08:10
Ok, I'lll try same file when you publish new release. But about another issue I commented here (I can open another one if you wish) , why yt-dlp is not closed when I close DZA??  I accidentally discovered that yt-dlp was the culprit that kept creating more and more fragments in my NFS folder because I looked at the active processes. There I discovered that despite shutting down DZA, yt-dlp was still active and uncontrollably creating files. I think that by closing DZA, DZA should close the yt-dlp launched thread.
