### ISSUE TITLE
[Bug] There is no progress bar update in 3.0.2 version, in 3.0.1 was OK

### ISSUE THREAD

**Issue by iG8R** [setvisible/DownZemAll#95] opened 2023-01-15 19:07 UTC
Hi.

"Progress" bar as well as "Percent", "Size", "Est.time" and "speed" don't update during download.
URL example: https://vk.com/video-164903675_456240608

![image](https://user-images.githubusercontent.com/11407417/212561753-d30a5560-a6ff-4b97-973c-6706a58dbd00.png)

**Comment by setvisible** [comment] 2023-04-01 15:04
Hi

Sorry I couldn't reproduce it.

Maybe a former version of yt-dlp, which didn't handle the vk.com 's progress stream properly? Perhaps try to update yt-dlp (if not automatically done) and retry. 

If you observe that the issue only happens with www.vk.com, the issue is certainly in yt-dlp, and it should be addressed to the yt-dlp 's project:
https://github.com/yt-dlp/yt-dlp

Regards

**Comment by setvisible** [comment] 2023-04-01 15:06
Similar to  #93

**Comment by iG8R** [comment] 2023-04-01 15:08
Thanks a lot for the response.
I have noticed that this issue occurs intermittently with videos from different sources.

**Comment by setvisible** [comment] 2023-04-01 16:56
Then yt-dlp is suspect number one for being the root cause :)

Perhaps address the issue to them?

**Comment by iG8R** [comment] 2023-04-01 17:16
Previously I've checked yt-dlp from command line with these "problematic" videos and it showed overall progress and speed without any issues but slightly in a different manner - it didn't change smoothly but somehow jittering, unstable.
Next time I come across a video like this, I'll post it in this thread, since the previous one I mentioned at the beginning was deleted.

**Comment by setvisible** [comment] 2023-04-01 20:49
Sure, give more feedback and urls if you face it again !

**Comment by setvisible** [comment] 2023-05-08 11:33
Fixed in v3.0.4

**Closed** 2023-05-08 11:33 UTC
Labels: bug

**Comment by RafaelLinux** [comment] 2023-05-13 23:00
Bad news. I test again to download same YT file with DZA 3.0.5 and same issue: DZA reaches 100% while continues dowloading (cause file really didn't downloaded completely). A lot of "filename_Frag~###" files begin to  be created till I cancel download.

**Comment by RafaelLinux** [comment] 2023-05-22 22:09
Please, this bug should not be closed, it's not working  :(
